package util

var (
	Filter = []string{
		"survey", "whatsapp", "24/7", "r/", "@gmail.com", "DM", "service", "call", "phone", "email",
	}
	Keywords = []string{
		"problem",
		"issue",
		"challenge",
		"difficulty",
		"struggle",
		"frustration",
		"obstacle",
		"barrier",
		"roadblock",
		"bottleneck",
		"headache",
		"nightmare",
		"hassle",
		"burden",
		"pain point",
		"snag",
		"glitch",
		"bug",
		"error",
		"fault",
		"defect",
		"flaw",
		"limitation",
		"shortcoming",
		"drawback",
		"downside",
		"disadvantage",
		"constraint",
		"restriction",
		"frustrated",
		"annoyed",
		"irritated",
		"stressed",
		"overwhelmed",
		"confused",
		"stuck",
		"lost",
		"hopeless",
		"disappointed",
		"unhappy",
		"terrible",
		"awful",
		"horrible",
		"why doesn't",
		"how do I fix",
		"what's wrong with",
		"why is this happening",
		"can't get this to work",
		"having trouble with",
		"need help with",
		"any ideas how to",
		"anyone else experiencing",
		"slow",
		"expensive",
		"complicated",
		"confusing",
		"difficult to use",
		"time-consuming",
		"inefficient",
		"unreliable",
		"inconvenient",
		"unclear",
		"doesn't work",
		"broken",
		"crashes",
		"error message",
		"bug report",
		"compatibility issue",
		"security concern",
		"troubleshooting",
		"fixing",
		"repairing",
		"debugging",
		"workaround",
		"solution",
		"alternative",
		"replace",
		"upgrade",
		"return",
		"worst",
		"terrible experience",
		"waste of time",
		"don't recommend",
		"not worth it",
		"very disappointed",
		"big mistake",
		"never again",
		"complete failure",
		"totally useless",
		"urgent",
		"critical",
		"asap",
		"important",
		"immediately",
		"cost",
		"inconvenience",
		"lack of features",
		"help needed",
		"serious problem",
		"major issue",
		"blocker",
	}
)
