name: Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"
      - name: Get dependencies
        run: |
          go mod download
      - name: Test with the Go CLI
        run: go test -v ./util/... ./internal/scraper/reddit/... ./internal/consumer/...
        env:
          TEST_PROXY: ${{ secrets.TEST_PROXY }}
